services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-tp01
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  laravel-agent:
    build: .
    container_name: jenkins-laravel-agent
    privileged: true
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpmWeF3Fulinxy1q4OC1YspJx2XaApus6ENpm9Z7qpBML6CGmApsOmldkzzAkXQpGqj3T8M3Ed827wYA1HD1dg2t6nepGnZbaUfSGc/U3Dv2ok8jW0vdV5U5R6fevficynBukCMSRcKBqg3K7oDUym5CeyYF8olZKlGkrvPBWJAj/Kr6bulBYGck7uJHpM7Rs9FjctZw8pX0ckC5izU2nq63XIY4kqmZHOGoWHTp6r5xNGUWuhsAOeTXmdSMhL2bduoZcybPvtqnhdtGS9bIxaD9yt7YGbUi40ej9FDpPcU3S+WzMmWcd6x9ZD6FVBuOmHgSGnCSAeAsj/5LAcuf98/+lAPH+vLqGTVvYMETULTgic1lJASlwmf7tK42RO+mc2dx6nV/+a4wZKIpA7zlfJz5s2tMfVdLU3SnZFmReZKcYpfoBobEEjbTvwz6EoP/ZmxnWTMLdunX0i1HTtXmahvMRTrw3Rf9XAik2576G/tsFnV5psP+gYu93pEqYc2tvqJgVGQJU/+bTZKVaoKLkUbG/AY/sbaZmAz/AhtVrTShetrggDTHlmfKx5w/Gw6nwyjnk/yFvUM4EQS0v9t6MmcZ8Zvjf4COLJvvdn0DnBfstzYkMDtG6/Ys1PLZqSuaqst4YvJ8S1SYWpZv5WIf4A+SgGxlM9Njnhr4NOqIWLiQ== macbook@MacBooks-MacBook-Pro-2.local

volumes:
  jenkins_home: